url: https://y7kim.github.io
baseurl: /agency-jekyll-theme/

# Site settings
#title: RAPP
title: <a class="brand-image" href=""><img class="brand-image" src="img/logo.png"/ height="62" width="82"></a> 
email: info@rapp-project.eu 
description: "An open-source software platform for developers to easily create and deliver robotics apps dedicated to social inclusion of elderly people."


# Team names, titles and social links
people:
- name: Kay Garland
  pic: 1
  position: Lead Designer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Larry Parker
  pic: 2
  position: Lead Marketer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Diana Petersen
  pic: 3
  position: Lead Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/RAPP_EU
  - title: linkedin
    url: https://www.linkedin.com/groups/7446892/profile
  - title: youtube
    url: https://www.youtube.com/channel/UC0xbT_hd9ePA7WnmbxgkuVg
  - title: feed 
    url: http://rapp-project.eu/feed/
 
# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
